// Danh sách nguồn tin chính thống, đọc trực tiếp qua RSS (proxy trong vite.config.js)
export const CATEGORIES = {
  tech: 'Công nghệ',
  finance: 'Tài chính',
  dev: 'Developer',
  stocknews: 'Tin tức CK',
  stockedu: 'Kiến thức CK',
}

export const FEEDS = [
  {
    id: 'vnexpress-khcn',
    source: 'VnExpress',
    category: 'tech',
    url: '/feeds/vnexpress/rss/khoa-hoc-cong-nghe.rss',
    homepage: 'https://vnexpress.net',
  },
  {
    id: 'tuoitre-congnghe',
    source: 'Tuổi Trẻ',
    category: 'tech',
    url: '/feeds/tuoitre/rss/cong-nghe.rss',
    homepage: 'https://tuoitre.vn',
  },
  {
    id: 'techcrunch',
    source: 'TechCrunch',
    category: 'tech',
    url: '/feeds/techcrunch/feed/',
    homepage: 'https://techcrunch.com',
  },
  {
    id: 'theverge',
    source: 'The Verge',
    category: 'tech',
    url: '/feeds/theverge/rss/index.xml',
    homepage: 'https://www.theverge.com',
  },
  {
    id: 'vnexpress-kinhdoanh',
    source: 'VnExpress',
    category: 'finance',
    url: '/feeds/vnexpress/rss/kinh-doanh.rss',
    homepage: 'https://vnexpress.net',
  },
  {
    id: 'tuoitre-kinhdoanh',
    source: 'Tuổi Trẻ',
    category: 'finance',
    url: '/feeds/tuoitre/rss/kinh-doanh.rss',
    homepage: 'https://tuoitre.vn',
  },
  {
    id: 'cafef-chungkhoan',
    source: 'CafeF',
    category: 'finance',
    url: '/feeds/cafef/thi-truong-chung-khoan.rss',
    homepage: 'https://cafef.vn',
  },
  {
    id: 'cnbc-finance',
    source: 'CNBC',
    category: 'finance',
    url: '/feeds/cnbc/id/10001147/device/rss/rss.html',
    homepage: 'https://www.cnbc.com',
  },
  {
    id: 'devto',
    source: 'Dev.to',
    category: 'dev',
    url: '/feeds/devto/feed',
    homepage: 'https://dev.to',
  },
  {
    id: 'github-blog',
    source: 'GitHub Blog',
    category: 'dev',
    url: '/feeds/githubblog/feed/',
    homepage: 'https://github.blog',
  },
  {
    id: 'stackoverflow-blog',
    source: 'Stack Overflow Blog',
    category: 'dev',
    url: '/feeds/soblog/feed/',
    homepage: 'https://stackoverflow.blog',
  },
  {
    id: 'freecodecamp',
    source: 'freeCodeCamp',
    category: 'dev',
    url: '/feeds/freecodecamp/news/rss/',
    homepage: 'https://www.freecodecamp.org',
  },
  {
    id: 'hackernews',
    source: 'Hacker News',
    category: 'dev',
    url: '/feeds/hnrss/frontpage',
    homepage: 'https://news.ycombinator.com',
  },
  {
    id: 'vietstock-market',
    source: 'Vietstock',
    category: 'stocknews',
    url: '/feeds/vietstock/144/chung-khoan.rss',
    homepage: 'https://vietstock.vn',
  },
  {
    id: 'vietstock-expert',
    source: 'Vietstock',
    category: 'stockedu',
    url: '/feeds/vietstock/145/chung-khoan/y-kien-chuyen-gia.rss',
    homepage: 'https://vietstock.vn',
  },
  {
    id: 'vietstock-stories',
    source: 'Vietstock',
    category: 'stockedu',
    url: '/feeds/vietstock/3355/chung-khoan/cau-chuyen-dau-tu.rss',
    homepage: 'https://vietstock.vn',
  },
  {
    id: 'motley-fool',
    source: 'The Motley Fool',
    category: 'stockedu',
    url: '/feeds/fool/feeds/index.aspx',
    homepage: 'https://www.fool.com',
  },
]
